//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JuegoAhorcadoEntities : DbContext
    {
        public JuegoAhorcadoEntities()
            : base("name=JuegoAhorcadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Dificultades> Dificultades { get; set; }
        public virtual DbSet<Jugadores> Jugadores { get; set; }
        public virtual DbSet<Palabras> Palabras { get; set; }
        public virtual DbSet<JugadoresPartidas> JugadoresPartidas { get; set; }
        public virtual DbSet<Partidas> Partidas { get; set; }
        public virtual DbSet<EstadosPartida> EstadosPartida { get; set; }
    }
}
