//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palabras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Palabras()
        {
            this.Partidas = new HashSet<Partidas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int IdDificultad { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionIngles { get; set; }
        public int IdCategoria { get; set; }
        public string NombreIngles { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Dificultades Dificultades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partidas> Partidas { get; set; }
    }
}
