//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partidas()
        {
            this.JugadoresPartidas = new HashSet<JugadoresPartidas>();
        }
    
        public int Id { get; set; }
        public int IdPalabraSelecionada { get; set; }
        public int IdEstadoPartida { get; set; }
        public System.DateTime FechaCreacionPartida { get; set; }
        public string IdiomaPartida { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPartidas> JugadoresPartidas { get; set; }
        public virtual Palabras Palabras { get; set; }
        public virtual EstadosPartida EstadosPartida { get; set; }
    }
}
